### ISSUE TITLE
Advanced queries

### ISSUE THREAD

**Issue by Axo-Fv** [Iceloof/GoogleNews#101]
Good afertnoon.
Recently I found this tool, and it's amazing! I was wondering, how much the query could be customized, in [this](https://developers.google.com/custom-search/docs/xml_results#wsSpecialQueryTerms) post I found how can you do advanced queries by special query terms on google. Some options like exclude and include term, even phrase search, are showed in the examples. So, what about options like **allintext:**. Is there a way to run this in a query with GoogleNews library?

**Comment by HurinHu** [comment]
you can add this option into keyword, like `googlenews.get_news("allintext:new zealand")`
