### ISSUE TITLE
hi. Are the results of Google News exactly the same as the results of the News section of Google? and is it possible to get the results of the web section of google with GoogleNews? How?thanks

### ISSUE THREAD

**Issue by frida96** [Iceloof/GoogleNews#105]

**Comment by frida96** [comment]
![Screenshot (250)](https://user-images.githubusercontent.com/72890078/186730841-59a77c1b-c95a-429e-94ba-48ed3e61a487.png)

**Comment by frida96** [comment]
and my secound question;
Does GoogleNews, like pygooglenews, have a time limit of 1000 requests per day? or something similar that.

**Comment by HurinHu** [comment]
get_news() is getting from https://news.google.com/search, search() is getting from https://www.google.com/search?q=apple&tbm=nws which is the screenshot you post. There is not specific requests limit from Google, as this library is only simulate you normal site visit, but I don't suggest you request too frequency, as it may easily recognized as robot by Google and block your IP address with some image verification.
