### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by umertahir13** [Iceloof/GoogleNews#108]
I used this library but when I could not find the page it prints nonetype object is not iterable but does not return exception in return which makes it impossible to identify on which page it will print the nonetype exception. Please return the exception so, in the script, this exception can be caught and this will help in identifying the page number for each search.

**Comment by HurinHu** [comment]
> I used this library but when I could not find the page it prints nonetype object is not iterable but does not return exception in return which makes it impossible to identify on which page it will print the nonetype exception. Please return the exception so, in the script, this exception can be caught and this will help in identifying the page number for each search.

Will added it in the next release.

**Comment by HurinHu** [comment]
The new release version is allowed to throw exception if you set `googlenews.enableException(True)`
