### ISSUE TITLE
Simple Help

### ISSUE THREAD

**Issue by shred66** [Iceloof/GoogleNews#111]
Hello
first of all i want to report that to me the version 1.6.6, in the project gets imported only if it is written like that: `from GoogleNews import GoogleNews` and not like `this from googlenews import GoogleNews` .

btw, how do i get only the headlines from the google news section "World" ? 
(sorry, i'm new to the world of coding)

Thank you for any help

**Comment by HurinHu** [comment]
As the README shows, you should use `from GoogleNews import GoogleNews` instead of `from googlenews import GoogleNews`, it is case sensitive. And currently the library is not supported to extract World section from news.google.com
