### ISSUE TITLE
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)>

### ISSUE THREAD

**Issue by KhalidAmine** [Iceloof/GoogleNews#118]
when conducting following script i get the following error: 

`def get_ethereum_news(start_date, end_date):
    # Initialize GoogleNews
    googlenews = GoogleNews(lang='en', start=start_date, end=end_date)

    # Search for Ethereum news
    googlenews.search('Ethereum')

    # Create a list to store news data
    news_data = []

    # Get the first 10 pages of search results
    for page in range(1, 11):
        googlenews.get_page(page)
        news_items = googlenews.results(sort=True)
        for item in news_items:
            news_data.append(item)
    
    # Create a DataFrame with the news data
    df = pd.DataFrame(news_data)

    # Set the DataFrame index to the news datetime
    df.set_index('datetime', inplace=True)

    # Clear search results
    googlenews.clear()

    return df`
    
    
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)>
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)>
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)>
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)>
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)>
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)>
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)>
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)>
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)>
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)>
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)>

**Comment by HurinHu** [comment]
It seems like your local environment has some issues with ssl certificate or runs behind proxy.
