### ISSUE TITLE
googlenews.search('APPLE')

### ISSUE THREAD

**Issue by alinemati-uwm** [Iceloof/GoogleNews#119]
Hello ,
when I ran this line of code

googlenews.search('APPLE')

return is 

'NoneType' object is not iterable

googlenews.get_page(2)
'NoneType' object is not iterable

**Comment by alinemati-uwm** [comment]
### MODULES

from GoogleNews import GoogleNews

### METHODS

def show_routine(results):
    for num,page in enumerate(results):
        print(f"{num}. {page['date']} - {page['title']}")
        
### MAIN

# Setup the research
keywords="covid cava de' tirreni"
period='10d'
google_news = GoogleNews(lang='it',period=period)
google=GoogleNews(lang='it',period=period)

# Results from news.google.com
google_news.get_news(keywords)
results_gnews=google_news.results(sort=True)
show_routine(results_gnews)

# Results from google.com
google.search(keywords)
results_google=google.results(sort=True)
show_routine(results_google)


0. 2 giorni fa - Cava de' Tirreni, dopo tre anni d'assenza torna il Beach Volley "Città ...
1. 5 giorni fa - Rassegna stampa: le prime pagine dei giornali salernitani del 5 agosto - Salernonotizie.it
'NoneType' object is not iterable

**Comment by HurinHu** [comment]
Have you tried to use
`
keywords="APPLE"
period='10d'
google_news = GoogleNews(period=period)
google=GoogleNews(period=period)
google_news.get_news(keywords)
results_gnews=google_news.results(sort=True)
print(results_gnews)
google.search(keywords)
results_google=google.results(sort=True)
print(results_google)
`

**Comment by alinemati-uwm** [comment]
yes,
I am looking to ahve 'desc': which return  None for any code. 

![image](https://github.com/Iceloof/GoogleNews/assets/138640810/fe5e8b8f-3921-486a-8ca4-cd3965196222)

**Comment by Troy1818** [comment]
Hello, I've also been encountering this issue for the last 12 hours. Prior to that the google.search(keyword) portion of the code was working wonderfully. However, now it outputs 'NoneType' object is not utterable. I've noticed the google_news.get_news(keywords) option still runs properly. Any other ideas on how to get google.search to not return a NoneType object?

**Comment by HurinHu** [comment]
It seems google change its web page source code recently, I will fixed it ASAP if I have time, or if some else fix it, can merge into this project.

**Comment by alinemati-uwm** [comment]
let me see if I can fix your code. 
I will keep you post it. 

by the way, when I ran below code, it includes the desc. it might help. **it is working now.**
@HurinHu 

```
from GoogleNews import GoogleNews
googlenews = GoogleNews()
googlenews.clear()
import pandas as pd

googlenews = GoogleNews(lang='en')
googlenews.get_news('india road accident')
googlenews.search('india road accident')

result_0 = googlenews.page_at(1)

desc_1 = googlenews.get_texts()
link_1 = googlenews.get_links()
link = googlenews.get_links()

for i in list(range(2, 5)):

    result = googlenews.page_at(i)
    desc = googlenews.get_texts()
    link = googlenews.get_links()

    desc_1 = desc_1 + desc
    link_1 = link_1 + link

... rest of code convert to pandas
...
```

![image](https://github.com/Iceloof/GoogleNews/assets/138640810/c8a26bee-ef3e-4a88-9d7f-a3f90d7d8aaf)

**Comment by Troy1818** [comment]
Hello again, I wanted to follow up to see if anyone has resolved the issue? I still received the same 'NoneType' object output this morning. I could also make an attempt at updating it over the weekend if others haven't been able to work on it. Thank you!

**Comment by alinemati-uwm** [comment]
Not yet. I am try to later.

**Comment by HurinHu** [comment]
New release v1.6.9 solve this issue, but `.total_count()` is not working with `.search()` anymore.

**Comment by alinemati-uwm** [comment]
thanks for update, I can see two bugs there

I search for chatgot to check
1. URL looks extra stuff which does not open the link
2.  'desc': '' is empty

Mycode:
`from GoogleNews import GoogleNews
googlenews = GoogleNews()
googlenews.enableException(True)
googlenews.set_lang('en')
googlenews.set_period('1d')
# googlenews.set_time_range('08/11/2023','02/28/2020')
googlenews.set_encode('utf-8')
googlenews.search('Chatgpt')
result = googlenews.page_at(2)
result`

My result:
`
[{'title': 'Hackers take on ChatGPT with support from White House',
  'media': 'CNN',
  'date': '6 hours ago',
  'datetime': datetime.datetime(2023, 8, 11, 20, 8, 33, 681797),
  'desc': '',
  'link': '/url?esrc=s&q=&rct=j&sa=U&url=https://www.cnn.com/videos/world/2023/08/11/exp-hackers-ai-vegas-lkl-081102pseg2-cnni-world.cnn&ved=2ahUKEwi11JzzhNaAAxUxm1YBHTz2Dx04ChDF9AF6BAgDEAI&usg=AOvVaw14nsFJTPwZeSPlNUzqrOE5',
  'img': 'data:image/gif;base64,R0lGODlhAQABAIAAAP///////yH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=='},
 `
