### ISSUE TITLE
googlenews.search not working

### ISSUE THREAD

**Issue by rajtrader** [Iceloof/GoogleNews#122]
It seems like googlenews.serach() is not working, I got empty results.
However, googlenews.get_news() is working fine.

**Comment by sabitm** [comment]
Both `search` and `get_news` returns `None` for me right now. Maybe there are changes from gnews?

**Comment by HurinHu** [comment]
I have double checked the latest version 1.6.9 and both function are working well. The issue might be google blocked your IP and required additional verification to proof human.
