### ISSUE TITLE
GoogleNews search is not working, please help

### ISSUE THREAD

**Issue by SamratDey112358** [Iceloof/GoogleNews#124]
googlenews.search("<any keyword") is giving "'NoneType' object is not iterable" in Python

**Comment by HurinHu** [comment]
Are you using the latest version? I can see both .get_news() and .search() can return a list of result with latest version

**Comment by SamratDey112358** [comment]
Hi, am using version 1.6.9

**Comment by HurinHu** [comment]
Try to use browser to open google and search something with same pc, and check whether Google does robot verification or not. This may be Google recognize your behaviour as robot and do extra verification, then will cause this issue. Otherwise it seems not code issue.

**Comment by SamratDey112358** [comment]
No I am not getting any message about Google doing robot verification, can search as usual on browser
also same issue in multiple systems
have also tried with different internet connections

**Comment by HurinHu** [comment]
```
user_agent = 'Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:64.0) Gecko/20100101 Firefox/64.0'
headers = {'User-Agent': user_agent}
url='https://www.google.com/search?q=%3Cany%20keyword&lr=lang_en&biw=1920&bih=976&source=lnt&tbs=lr:lang_1en,qdr:10d,,sbd:1&tbm=nws&start=0'
req = urllib.request.Request(url.replace("search?","search?hl="+self.__lang+"&gl="+self.__lang+"&"), headers=headers)
response = urllib.request.urlopen(req)
page = response.read()
```
Try this code and see whether you can get the details

**Comment by SamratDey112358** [comment]
"self" is not defined, can I change it to "en"?

**Comment by HurinHu** [comment]
> "self" is not defined, can I change it to "en"?

yes, just set your language

**Comment by SamratDey112358** [comment]
it ran, there is an output for page which is a huge chunk of string like this "b'<!doctype html><html lang="en-IN"><head><meta charset="UTF-8"><meta content="origin" name="referrer"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>&lt;any keyword - Google Search</title><script nonce="6vxUfkd6PyUHdTRbAUknnA">(function(){\ndocument.documentElement.addEventListener("submit",function(b){var a;if(a=b.target){var c=a.getAttribute("data-submitfalse");a="1"===c||"q"===c&&!a.elements.q.value?!0:!1}else a=!1;a&&(b.preventDefault(),b.stopPropagation())},!0);document.documentElement.addEventListener("click",function(b){var a;a:{for(a=b.target;a&&a!==document.documentElement......."

**Comment by SamratDey112358** [comment]
Hi, any ideas?

**Comment by HurinHu** [comment]
try to open the url directly, and then find some title, try to search the title in this string, or you can try the source code https://github.com/Iceloof/GoogleNews/blob/master/GoogleNews/__init__.py
