### ISSUE TITLE
.search() does not take into account time range, gives limited number of results

### ISSUE THREAD

**Issue by SamratDey112358** [Iceloof/GoogleNews#125]
Hi, I have tested with the source code, the results are not having the correct time range (for instance if I set the time range as last 7 days, getting news items which are months old) and also for a single search, am only getting maximum 6 results even when no such limit is mentioned in the code. Please help.

**Comment by HurinHu** [comment]
`print(googlenews.getVersion())` make sure you are using latest version v1.6.10.
Any datetime/period/language/region filter are not guaranteed the accuracy by Google itself.
