### ISSUE TITLE
googlenews.search() giving empty results and desc is returning None

### ISSUE THREAD

**Issue by deepeshpalkar23** [Iceloof/GoogleNews#126]
![image](https://github.com/Iceloof/GoogleNews/assets/116352012/64853227-9b69-4f71-afd0-076d661533e4)
Below is the Desc: None issue I get after using googlenews.get_news().

{'title': "Chandrayaan-3 on Moon: What's next for Isro?", 'desc': None, 'date': '1 hour ago', 'datetime': datetime.datetime(2023, 8, 24, 15, 35, 24, 838487), 'link': 'news.google.com/./articles/CBMihQFodHRwczovL3d3dy5pbmRpYXRvZGF5LmluL3NjaWVuY2UvY2hhbmRyYXlhYW4tMy9zdG9yeS9jaGFuZHJheWFhbi0zLW1vb24tbGFuZGluZy1zdWNjZXNzLXVwZGF0ZS13aGF0LW5leHQtZm9yLWlzcm8tMjQyNjAwMS0yMDIzLTA4LTI00gGJAWh0dHBzOi8vd3d3LmluZGlhdG9kYXkuaW4vYW1wL3NjaWVuY2UvY2hhbmRyYXlhYW4tMy9zdG9yeS9jaGFuZHJheWFhbi0zLW1vb24tbGFuZGluZy1zdWNjZXNzLXVwZGF0ZS13aGF0LW5leHQtZm9yLWlzcm8tMjQyNjAwMS0yMDIzLTA4LTI0?hl=en-IN&gl=IN&ceid=IN%3Aen', 'img': 'https://lh3.googleusercontent.com/j-SksL4QtjE2r3D4GlVtvwoa_gW2mlDkePl8l2FJiC4y9o84JhDXQT9ETfsmPDDlcm4ruM4q9QA=s0-h14-rp', 
'media': 'India Today', 'site': None},

**Comment by HurinHu** [comment]
`print(googlenews.getVersion())` make sure you are using latest version v1.6.10.
As google updated its structure, `get_news()` no longer provide description.
