### ISSUE TITLE
Fetching doesnt work since 2 days

### ISSUE THREAD

**Issue by Denon9205** [Iceloof/GoogleNews#127]
The bot has not fetched any news for 2 days (according to the log). Was there again a change in the Google News structure?

**Comment by HurinHu** [comment]
I have tested `get_news()` and `search()` function, it seems both are working properly. Probably you need to check your IP is not being blocked or challenged by Google with robot verification

**Comment by tin8420** [comment]
The problem hasn't been solved yet, the news we got still empty @HurinHu would you please check again? 
thanks a lot!

**Comment by HurinHu** [comment]
> The problem hasn't been solved yet, the news we got still empty @HurinHu would you please check again? 
> 
> thanks a lot! 
I tried again with latest version, both functions are working fine.
![image](https://github.com/Iceloof/GoogleNews/assets/3132148/82b795eb-bed5-43fe-9fe9-bb07387e84ec)

**Comment by tin8420** [comment]
@HurinHu  Thanks for update, I upgraded my package version to 1.6.10 and seems to be work but the URL is containning so many extra stuffs which we can access the URL properly, would you able to take a look?  
Thanks so much
