### ISSUE TITLE
Pt-br version is not working

### ISSUE THREAD

**Issue by cae-vatiero** [Iceloof/GoogleNews#142]
Hey, I'm trying to use the portuguese from brasil version and it is not working. I used the code "googlenews.set_lang('pt-br')" and also "googlenews = GoogleNews(lang='pt', region='BR')". The result is "None" everytime that I search for something. 

There is a way to solve this problem? Thanks!

**Comment by HurinHu** [comment]
try this `GoogleNews(lang='pt-br')` with latest version 1.6.13
