### ISSUE TITLE
GoogleNews更新問題

### ISSUE THREAD

**Issue by yen0612** [Iceloof/GoogleNews#24]
更新之後原本關鍵字搜尋抓到的爬蟲新聞變成跟google新聞不同步，時間也亂跳，正常來說應該是抓取關鍵字查詢的新聞，可是更新之後都不知道抓到了什麼...
這是舊版本先前抓到的
![googlenews](https://user-images.githubusercontent.com/64542577/80610220-aa35ae80-8a6b-11ea-8f36-a852514ece4b.JPG)
後來舊版本程式碼跑不出media跟 date
![擷取](https://user-images.githubusercontent.com/64542577/80610563-16b0ad80-8a6c-11ea-8fa3-7bbbba9c7087.JPG)
後來想說更新一下看media跟 date會不會出來，結果出來是出來了，可是新聞不同步
![error](https://user-images.githubusercontent.com/64542577/80610373-de10d400-8a6b-11ea-95e0-bb5c2f8452b3.JPG)

**Comment by HurinHu** [comment]
在最新版本裡，

> 更新之後原本關鍵字搜尋抓到的爬蟲新聞變成跟google新聞不同步，時間也亂跳，正常來說應該是抓取關鍵字查詢的新聞，可是更新之後都不知道抓到了什麼...
> 這是舊版本先前抓到的
> ![googlenews](https://user-images.githubusercontent.com/64542577/80610220-aa35ae80-8a6b-11ea-8f36-a852514ece4b.JPG)
> 後來舊版本程式碼跑不出media跟 date
> ![擷取](https://user-images.githubusercontent.com/64542577/80610563-16b0ad80-8a6c-11ea-8fa3-7bbbba9c7087.JPG)
> 後來想說更新一下看media跟 date會不會出來，結果出來是出來了，可是新聞不同步
> ![error](https://user-images.githubusercontent.com/64542577/80610373-de10d400-8a6b-11ea-95e0-bb5c2f8452b3.JPG)

在最新版本裡，period的默認參數被刪除了，增加了自定義時間設置，如果你需要當天的數據，可以用`google news = GoogleNews(period='d')`，這個應該是跟之前的版本一樣的結果。在最新的readme上有具體的參數設置。

**Comment by wastu01** [comment]
最新版本中，搜尋字詞有些會因為特殊格式無法抓取
search in 台灣 ，如圖所示
<img width="605" alt="taiwan" src="https://user-images.githubusercontent.com/47618277/97779911-390eb980-1bbc-11eb-9c9c-3354efa54905.png">
<img width="519" alt="截圖 2020-10-31 下午8 48 15" src="https://user-images.githubusercontent.com/47618277/97779915-3ca24080-1bbc-11eb-9faf-98291c91d4ed.png">
