### ISSUE TITLE
How to get all article title?

### ISSUE THREAD

**Issue by Giovanni993** [Iceloof/GoogleNews#44]
Is there a way to get the entire title during a research? For example: I search "Biden's win" with Google News. The title of a result is "Alaska Sen. Dan Sullivan acknowledges President-elect Joe..." , and not "Alaska Sen. Dan Sullivan acknowledges President-elect Joe Biden’s win".

**Comment by HurinHu** [comment]
At current stage, Google is not showing full text on the search result, so it's not possible to get the full text unless you read all the link to complete it. But that is not a good idea.

**Comment by Giovanni993** [comment]
Thank you and happy new year

Il ven 1 gen 2021, 11:09 Hurin Hu <notifications@github.com> ha scritto:
