### ISSUE TITLE
Blacklisted by Google News?

### ISSUE THREAD

**Issue by gtangg12** [Iceloof/GoogleNews#47]
I have a script that returns nothing, but my friend can scrape using the same script. I assume Google ip banned me? I only scraped like 200 article urls.

**Comment by HurinHu** [comment]
Are you able to get the result at first try? I assume your IP is blocked by Google, to avoid this, you can add some random delay between the requests.

**Comment by gtangg12** [comment]
No, unfortunately. Apparently, Google sets limited requests from a IP per month or something. I was able to scrape using sitemap of the news site. Too lazy to look into changing ip etc...
