### ISSUE TITLE
partially initialized module 'GoogleNews' has no attribute 'get_news' (most likely due to a circular import)

### ISSUE THREAD

**Issue by digish777** [Iceloof/GoogleNews#68]
partially initialized module 'GoogleNews' has no attribute 'get_news' (most likely due to a circular import)

cannot import name 'GoogleNews' from partially initialized module 'GoogleNews' (most likely due to a circular import)

**Comment by HurinHu** [comment]
```
from GoogleNews import GoogleNews
googlenews = GoogleNews()
googlenews.get_news('APPLE')
googlenews.results()
```
You should able to get the result from this
