### ISSUE TITLE
[Error] Missing/Empty data entries when deploying to railway.app

### ISSUE THREAD

**Issue by buinguyenhoangtho** [Iceloof/GoogleNews#69]
Hello author. I want to report this strange bug. 

I tested on local with your library and still working normal. the "entries" part is still exists:
https://pastebin.com/xYs8pmkv
```json
..........
'entries': [
    {
      'title': 'Angela Merkel tiêm vaccine: Liều một AstraZeneca, liều hai Moderna - BBC Tiếng Việt',
      'title_detail': {
        'type': 'text/plain',
        'language': None,
        'base': '',
        'value': 'Angela Merkel tiêm vaccine: Liều một AstraZeneca, liều hai Moderna - BBC Tiếng Việt'
      },
......
```
But when im trying to deployed on https://railway.app/, the entries somehow return an empty "entries" 
The log: https://pastebin.com/Sj5ARuVN
```json
....
 'entries': [
    // empty
  ]
```
The code im using
```python
gn = GoogleNews(lang = 'vi')
    search = gn.search('Covid-19', when = '1h')
    print(search) 
    entries = search['entries']
    print(entries)
```

**Comment by HurinHu** [comment]
The reason is your server(IP) was recognized as robot by Google, which means google is not allowed people to use its services on cloud server through script.

**Comment by buinguyenhoangtho** [comment]
So can you recommend alternative soi, library for news ? 😢

**Comment by HurinHu** [comment]
> So can you recommend alternative soi, library for news ? 😢 

Probably no api can do this at the moment. Because Google blocks the IP from cloud server provider, which means anything get from google automatically can not be run on cloud server.
