### ISSUE TITLE
HTTP 429 error

### ISSUE THREAD

**Issue by sheetal158** [Iceloof/GoogleNews#70]
Getting the following error

HTTP Error 429: Too Many Requests

Any clues to fix this?

**Comment by alexgg278** [comment]
Same problem

**Comment by meetdoshi90** [comment]
Can you post the code for your http request?

**Comment by HurinHu** [comment]
You need to set delay time between requests, if too many requests from same IP, it might recognize you as robot and restrict or block your IP.

**Comment by devpladinc** [comment]
Encountered same error. Applied delay if for sending frequent API requests.

**Comment by piersym667** [comment]
Hello. this error is usually caused by proxy or vpn usage... please turn off your vpn or proxy and try
