### ISSUE TITLE
Can't get full descriptions

### ISSUE THREAD

**Issue by ChelsyMena** [Iceloof/GoogleNews#74]
Thanks for the nifty library, I haven't encountered any issues per se. It's just, when I run a search, I get a random bit of text that can be somewhere in the middle of the news article in question, not really a summary of the news like I though it would, and even then it's cutoff either at the beginning or the end with ellipsis. I'd like to get a full paragraph, or maybe even the full text, is there anything I can modify in the code to get this?

**Comment by HurinHu** [comment]
The summary will be something like what you see in google news search page, and with will be partial text, as it is not showing full text in the result page.

**Comment by ChelsyMena** [comment]
That's the thing, it isn't. It's like a sentence from some middle point of the article and often it isn't even complete. I went and checked. I'm getting stuff like:

> "The company was sold last June, valued on 30 Million ..."

I look it up in google news manually, and there's no description in their redesigned page and I open the article and the quote will be there in the second or third paragraph.

**Comment by HurinHu** [comment]
https://www.google.com/search?q=covid&safe=active&sxsrf=ALeKk00xFWsYOGaeDR0IQDN_olzfbH5m_Q:1629773899791&source=lnms&tbm=nws&sa=X&ved=2ahUKEwjvsvHy1MjyAhVUbysKHUCjBJ4Q_AUoAXoECAEQAw&biw=1536&bih=754 
something like this, the summary is just under the title, and usually it is not a completed paragraph.

**Comment by ChelsyMena** [comment]
Oh, okay. They got rid of it in the redesign, hence my confusion as to where it was choosing to pluck the random sentence from

https://news.google.com/topics/CAAqBwgKMJy5lwswj-KuAw?hl=en-US&gl=US&ceid=US%3Aen
It's just headlines and tweets now

Thanks a lot!
