### ISSUE TITLE
Region not working

### ISSUE THREAD

**Issue by kiddkrypto** [Iceloof/GoogleNews#76]
I have tried using the region option but I get an error.

**Comment by HurinHu** [comment]
Region parameter is not always working, as it is not part of google search, it can only restrict to the language like this,
```
googlenews = GoogleNews(period='7d', encode='utf-8', lang='zh-CN', region='CN')
googlenews.search('Covid-19')
```

**Comment by kiddkrypto** [comment]
From your example that should work right? I am getting an error when I use that that region flag.

**Comment by HurinHu** [comment]
What error do you get? This example should work with Chinese characters result.

**Comment by kiddkrypto** [comment]
For Chinese or any region is get "got an unexpected keyword argument 'region'"

**Comment by HurinHu** [comment]
Is seems you are using old version, please follow the Readme to upgrade to latest version

**Comment by kiddkrypto** [comment]
Ok thank you that did work. 

One more question around this, my server in the USA will work for fetching Google for sentiment analysis but in Brazil it doesn't work for more than 20 minutes before it gets an error of 'http error 429: too many requests' 

I have the same code on my usa server but doesn't have this error. 

Can you point me in the right direction for this?

**Comment by HurinHu** [comment]
It is not suggested to use on server, cloud server usually will be recognized as robot by Google and it may be easily exceed the maximum request rates or even blocked.

**Comment by kiddkrypto** [comment]
Ok, so my problem is I have an algorithm that is using the Google news feeds but the exchange that I need to use doesn't work for USA people. While back testing from my us server it works but even backtesting from a server outside of us it doesn't work for longer than 30 minutes. 

How would I get around this?

**Comment by HurinHu** [comment]
If it can work sometimes, but not longer than 30 minutes, then you might need to set some random delays between calls

**Comment by wastu01** [comment]
It worked for me in Traditional Chinese using this:
```python
googlenews = GoogleNews(lang='zh-tw', region='TW', encode='utf-8', period='1d')
```

Here is the official Google documentation regarding the search parameters (if someone need it):
- `hl` sets the user interface language.
- `gl` searches news based on the user's geographic location.
- `lr` returns search results primarily in a specific language.
- [hl interface language codes](https://developers.google.com/custom-search/docs/json_api_reference?hl=zh-tw#interfaceLanguages)
- [gl country/region codes](https://developers.google.com/custom-search/docs/json_api_reference?hl=zh-tw#countryCodes)
- [lr language filter](https://developers.google.com/custom-search/v1/reference/rest/v1/cse/list?hl=zh-tw)

(btw, I noticed that both `zh-tw` and `zh-TW` work fine.)
