### ISSUE TITLE
Search is returning empty list

### ISSUE THREAD

**Issue by former-economist** [Iceloof/GoogleNews#93]

**Comment by former-economist** [comment]
When search for a popular subject it returns an empty list.

`from GoogleNews import GoogleNews
googlenews = GoogleNews()
googlenews.search("Raspberry Pi")
results = googlenews.results()
print(f"Number of results {len(results)}.")
print(f"First result: {results}")`

Giving the following output:
Number of results 0.
First result: []

**Comment by SamratDey112358** [comment]
Same issue since today. Search function is not working but get_news is working.

**Comment by HurinHu** [comment]
The issue is solved with latest version, please upgrade to v1.6.4
