### ISSUE TITLE
Search is returning empty list

### ISSUE THREAD

**Issue by SamratDey112358** [Iceloof/GoogleNews#94]
googlenews.search(item) is giving empty list. Since we need to extract news content from site urls, get_news function  - which gives the urls in a different format, I think - is not suitable. Tried upgrading googlenews package but to no avail. Please help! Thanks

**Comment by la-strole** [comment]
Looks like Google changed the tags again. In the file __init__.py you can replace  line 139 
`result = self.content.find_all("div", id="search")[0].find_all("g-card")`
 with 
`result = self.content.find_all("div", id="search")[0].find("div", id="rso").children`
[https://drive.google.com/file/d/1oRq5BRVEsFBlwpNWmaWdvCbLgniUku6U/view?usp=sharing](url)

**Comment by HurinHu** [comment]
The issue is solved with latest version, please upgrade to v1.6.4
