### ISSUE TITLE
HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by chinni505** [Iceloof/GoogleNews#98]
what is the limit of no.of requests per day? 
while using this python module getting below error.

HTTP Error 429: Too Many Requests

**Comment by HurinHu** [comment]
There is no official definition about this, it depends on your frequency and the requests from your IP address.

**Comment by kryukovaeks** [comment]
Hello,
How to change the frequency?

**Comment by HurinHu** [comment]
> Hello,
> 
> How to change the frequency?

You can add delay between calls.
